version: '3'

networks:
  my_network:
    driver: bridge

services:
  app:
    container_name: dockt-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - '3000:3000'
    env_file: '.env'
    volumes:
      - ./src:/opt/doct-api/src
    depends_on:
      - db
      - redis
  db:
    container_name: postgres_container_doct-db
    image: kartoza/postgis:12.0
    networks:
      - my_network
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .docker/data/db/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=doct-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hoang@1234

  mongo:
    container_name: mongo_container_doct-db
    image: mongo:latest
    restart: always
    networks:
      - my_network
    ports:
      - 27017:27017
    volumes:
      - .docker/data/db/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hoangtran
      - MONGO_INITDB_ROOT_PASSWORD=hoang1234

  redis:
    container_name: redis_container_doct-db
    image: bitnami/redis
    networks:
      - my_network
    volumes:
      - .docker/data/db/redis:/bitnami/redis/data
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
