service: doct-api-dev

custom:
  serverless-offline:
    useChildProcesses: true
  baseName: ${env:BASE_NAME, 'doct-api'}
  s3BucketName: ${self:custom.baseName}-s3-bucket
  sqs: ${self:custom.baseName}-message-queue
  sqs-dlq: ${self:custom.baseName}-message-dead-letter-queue
  stage: ${opt:stage, 'local'}
  awsAccountIdByStage:
    local: '000000000000'
    dev: ${env:AWS_ACCOUNT_ID, '000000000000'}
    stg: ${env:AWS_ACCOUNT_ID, '000000000000'}
    prod: ${env:AWS_ACCOUNT_ID, '000000000000'}

  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
    packager: 'yarn'

  prune:
    automatic: true
    includeLayers: true
    number: 3

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'ap-southeast-1'}
  stage: ${self:custom.stage}

  environment:
    NODE_ENV: ${self:custom.stage}
    APP_ENV: ${self:custom.stage}
    REGION: ${opt:region, 'ap-southeast-1'}
    NORMAL_QUEUE_URL: { Ref: MessageQueue }
    DB_URL: ${env:DB_URL}
    ALLOW_REAL_AWS: ${env:ALLOW_REAL_AWS, 'false'}

  vpc:
    securityGroupIds:
      - sg-0d0a771c00a4491c5
    subnetIds:
      - subnet-0a8ee345922b2bc68

  apiGateway:
    shouldStartNameWithService: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - { Fn::Join: ['', [{ Fn::GetAtt: [S3Bucket, Arn] }, '*']] }
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - { Fn::GetAtt: [MessageQueue, Arn] }
            - { Fn::GetAtt: [DeadLetterQueue, Arn] }

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  - ${file(./resources/lambdas/clientServer.yml)}
  - ${file(./resources/lambdas/sqsWorker.yml)}
  - ${file(./resources/lambdas/connectionServer.yml)}
  - ${file(./resources/lambdas/testServer.yml)}

resources:
  - ${file(./resources/s3.yml)}
  - ${file(./resources/sqs.yml)}
