Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, POST, PUT]
            AllowedOrigins: ['*']
      BucketName: ${self:custom.s3BucketName}
